apiVersion: v1
name: apache-sqoop-acmis
description: "First version by ACMIS. ."
type: application

home: http://sqoop.apache.org/
icon: http://sqoop.apache.org/images/sqoop-logo.png

# 添加图表
version: 0.1.6
