apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flink
  labels:
    app: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
    spec:
      containers:
        - name: flink
          image: flink:scala_2.12
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]

