apiVersion: v1
kind: Service
metadata:
    name: hadoop-service
spec:
    type: NodePort
    ports:
    - name: hadoop-socket
      port: 31001 # 内部通过这个端口访问
      targetPort: 22 # Docker 暴露出来的接口
#      nodePort: 30001 # node 机器暴露的端口
    - name: hadoop-hdfs
      port: 31002 # 内部通过这个端口访问
      targetPort: 9870 # Docker 暴露出来的接口
#      nodePort: 30002 # node 机器暴露的端口
    selector:
      app: admichadoop
#    type: NodePort
#    type: LoadBalancer
#    ports:
#    - port: 2200 # 外部通过这个端口访问
#      targetPort: 22 # Docker 暴露出来的接口
#    selector:
#      app: admichadoop