apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: greenplum
  labels:
    app: greenplum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenplum
  template:
    metadata:
      labels:
        app: greenplum
    spec:
      containers:
        - name: greenplum
          image: datagrip/greenplum:6.1
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]

